### ISSUE TITLE
Renaming Methods in Day.java

### ISSUE THREAD

**Issue by joeryhuiden** [wouterfennis/borg_calendar#4]
Example: 

Line 410: `private static int nthdom(int year, int month, int dayofweek, int week)`

**Comment by wouterfennis** [comment]
Over het algemeen was dit op een aantal plekken nodig.
Echter binnen de Day klasse hebben wij dit niet overal kunnen doen aangezien van buiten af en sterk belang is bij het behouden van sommigen namen. En we wilde ook weer niet dat we door één herbenoeming direct 10+ bestanden moesten aanpassen
